### ISSUE TITLE
Plans for PCB

### ISSUE THREAD

**Issue by syed** [rampadc/arduino-thinkpadkb-usb#1]
Hi,

Can I please have the plans for the PCB? I am trying to build it  and would be super stoked if you could provide the PCB plans.

**Comment by mike20030405** [comment]
I'd like to learn and study the PCM plans too!

**Comment by lorenzhs** [comment]
It's not the same board but https://flashandrc.files.wordpress.com/2016/07/thinkclamp_v0-6-2.pdf contains the schematics for the PCB that @rampadc sold over tindie. Might be possible to get it to work (parts are in the [tindie](https://www.tindie.com/products/rampadc/thinkpad-usb-keyboard-adapter-v061-rev-11-pcbreceptacle/)). Links at https://flashandrc.wordpress.com/2014/08/03/support-faq-customize-keyboard-matrix/

**Comment by rampadc** [comment]
I don't have the Arduino-based PCB & schematics anymore. This project was dropped completely because accessing a single microcontroller's I/Os is much faster, cheaper and more condensed than using a smaller ATmega (ie. the Arduino Leonardo or Micro) with external I/Os expander be it with SPI or I2C.
